Update DatabaseSeeder.php
andrisan-ub/pbd-e-2022 pull request #65
Opened 2022-09-22 05:21 UTC by meidadela

2022-09-24 08:04 UTC, andrisan-ub requested changes
Ini belum selesai?

2022-09-24 14:59 UTC, meidadela commented
Mohon maaf bapak, itu tugasnya sudah saya kumpulkan tapi sepertinya
terhapus. Akan saya coba untuk mengembalikan filenya pak.Sekali lagi mohon
maaf pak🙏🏻

On Sat, 24 Sept 2022, 3:04 pm andrisan-ub, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Ini belum selesai?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/andrisan-ub/pbd-e-2022/pull/65#pullrequestreview-1119204946>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVZGP7WYTKT3YGCTIPAFV7TV72YZVANCNFSM6AAAAAAQSV4CM4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-27 13:56 UTC, andrisan-ub requested changes
seeder jangan dituliskan di class DatabaseSeeder

2022-09-28 08:16 UTC, andrisan-ub approved these changes

2022-09-28 08:17 UTC, merged